# On push to master branch:
# 1. Build Docker image
# 2. Push to AWS ECR
image: atlassian/default-image:2

pipelines:
  branches:
    master:
      - step:
          name: Build and push image to ECR
          caches:
            - docker
          services:
            - docker
          script:
            # get the version
            - declare -x VERSION=$(cat version.txt)
            # build the image
            - docker build -t tdb-generation .
            # push image to AWS ECR
            - pipe: atlassian/aws-ecr-push-image:1.5.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                IMAGE_NAME: tdb-generation
                TAGS: $VERSION
