# On push to master branch:
# 1. Build Docker image
# 2. Push to AWS ECR
image: atlassian/default-image:2

pipelines:
  branches:
    master:
      - variables:
          - name: VERSION
      - step:
          name: Build and push image to ECR
          caches:
            - docker
          services:
            - docker
          script:
            # build the image
            - docker build -t tdb-generation:$VERSION --build-arg $VERSION .
            # push image to AWS ECR
            - pipe: atlassian/aws-ecr-push-image:1.5.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                IMAGE_NAME: tdb-generation
