services:

  test-basic:
    profiles:
      - test-basic
    build: .
    environment:
      JENA_VERSION: 5.5.0
      TEXT: true
      SPATIAL: true
    volumes:
      - type: bind
        source: tests/data
        target: /rdf
      - type: bind
        source: tests/config.ttl
        target: /config.ttl

  test-filenames:
    profiles:
      - test-filenames
    build: .
    volumes:
      - type: bind
        source: tests/bad_data
        target: /rdf

  test-persist:
    profiles:
      - test-persist
    build: .
    volumes:
      - type: bind
        source: tests/data
        target: /rdf
      - type: bind
        source: tests/tdb/
        target: /fuseki/databases

  test-indexonly:
    profiles:
      - test-indexonly
    build: .
    environment:
        SKIP_LOAD: true
        SPATIAL: true
    volumes:
      - type: bind
        source: tests/tdb/ds
        target: /fuseki/databases/ds

  test-jvmargs:
    profiles:
      - test-jvm
    build: .
    environment:
        USE_XLOADER: true
        JVM_ARGS: -Xmx6G
    volumes:
      - type: bind
        source: tests/data
        target: /rdf
