services:
  tdb2-generation:
    build: .
    environment:
      TEXT: true
      SPATIAL: true
      JENA_VERSION: 5.5.0
    volumes:
      - type: bind
        source: tests/data
        target: /rdf
      - type: bind
        source: tests/config.ttl
        target: /config.ttl
